version: 2

jobs:
  build:
    working_directory: ~/ballotpreview

    docker:
      - image: circleci/python:3.11

    steps:
      - checkout

      - run:
          name: Checking System Dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{{ checksum "poetry.lock" }}

      - run:
          name: Installing Project Dependencies
          command: make install

      - type: cache-save
        key: poetry-{{ checksum "poetry.lock" }}
        paths:
          - .venv

      - run:
          name: Checking Code
          command: make check

      - run:
          name: Running Tests
          command: make test && sudo pip install coveralls && coveralls

      - store_artifacts:
          path: htmlcov
