version: 2.1

jobs:
  build:
    working_directory: ~/ballotpreview

    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Checking System Dependencies
          command: make doctor

      - restore_cache:
          key: poetry-{{ checksum "poetry.lock" }}

      - run:
          name: Installing Project Dependencies
          command: make install

      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - .venv

      - run:
          name: Checking Code
          command: make check

      - run:
          name: Running Tests
          command: make test

      - store_artifacts:
          path: htmlcov
