[tool.poetry]

name = "ballotshare"
version = "1.0"
description = "Share how you plan to vote in Michigan."

authors = ["Citizen Labs <info@citizenlabs.org>"]
license = "GPLv3"

packages = [
    { include = "app" },
]

[tool.poetry.dependencies]

python = "^3.7"

# Server
quart = "~0.12.0"
bugsnag = "^3.6.0"

# Images
pillow = "^7.0"

# Utilities
aiohttp = "^3.6.2"
minilog = "=1.4b2"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=5.5.3"
black = "=20.8b1"

# Type Checking
mypy = "*"
pylint = "^2.4.4"

# Testing
pytest = "^5.0"
pytest-asyncio = "*"
pytest-vcr = "*"
pytest-describe = "^1.0"
pytest-expecter = "^2.0"
pytest-cov = "^2.7"
pytest-watch = "^4.2"

# Coverage
coveragespace = "^3.1"

# Utilities
honcho = "^1.0"
rope = "^0.14.0"

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
