[tool.poetry]

name = "ballotpreview"
version = "1.0"
description = "Share how you plan to vote in Michigan."

authors = ["Citizen Labs <info@citizenlabs.org>"]
license = "GPLv3"

packages = [{ include = "app" }]

[tool.poetry.dependencies]

python = "^3.10"

# Server
quart = "~0.16.2"

# Images
pillow = "^9.3"

# Utilities
aiohttp = "^3.7.4"
minilog = "^2.0"

# Production
bugsnag = "^4.0"
gunicorn = "~20.0.4"
uvicorn = "~0.18.3"

# Formatting
black = "~22.10"
tomli = "*" # missing 'black' dependency
isort = "~5.10"

# Type Checking
mypy = "^0.902"
pylint = "~2.15"
types-cryptography = "*"

# Testing
pytest = "^7.2"
exceptiongroup = "*" # missing 'pytest' dependency
pytest-asyncio = "*"
pytest-vcr = "*"
pytest-describe = "^2.0"
pytest-expecter = "^3.0"
pytest-cov = "^2.7"
pytest-watch = "^4.2"
pomace = { version = "~0.9.3", optional = true }

# Coverage
coveragespace = "^6.0"

# Utilities
honcho = "^1.0"
rope = "^0.14.0"

[tool.poetry.extras]

e2e = ["pomace"]

[tool.black]

quiet = true

[tool.isort]

profile = "black"

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
