[tool.poetry]

name = "ballotshare"
version = "1.0"
description = "Share how you plan to vote in Michigan."

authors = ["Citizen Labs <info@citizenlabs.org>"]
license = "GPLv3"

packages = [{ include = "app" }]

[tool.poetry.dependencies]

python = "^3.7"

# Server
quart = "~0.12.0"

# Images
pillow = "^8.2"

# Utilities
aiohttp = "^3.7.4"
minilog = "^2.0"

# Production
bugsnag = "^4.0"
gunicorn = "~20.0.4"
uvicorn = "~0.11.8"

# Formatting
isort = "=5.5.3"
black = "=20.8b1"

# Type Checking
mypy = "*"
pylint = "^2.4.4"

# Testing
pytest = "^5.0"
pytest-asyncio = "*"
pytest-vcr = "*"
pytest-describe = "^1.0"
pytest-expecter = "^2.0"
pytest-cov = "^2.7"
pytest-watch = "^4.2"
pomace = { version = "~0.7.3", optional = true }

# Coverage
coveragespace = "^4.0"

# Utilities
honcho = "^1.0"
rope = "^0.14.0"

[tool.poetry.extras]

e2e = ["pomace"]

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
