locators:
  inclusions:
    -
  exclusions:
    -
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: name
        value: first_name
        index: 0
        uses: 2
  - verb: fill
    name: last_name
    locators:
      - mode: name
        value: last_name
        index: 0
        uses: 7
  - verb: fill
    name: birth_date
    locators:
      - mode: name
        value: birth_date
        index: 0
        uses: 9
  - verb: fill
    name: zip_code
    locators:
      - mode: name
        value: zip_code
        index: 0
        uses: 7
  - verb: click
    name: find_your_ballot
    locators:
      - mode: text
        value: Find Your Ballot
        index: 0
        uses: 7
  - verb: click
    name: about
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: About
        index: 0
        uses: -1
      - mode: text
        value: About
        index: 0
        uses: -1
      - mode: value
        value: About
        index: 0
        uses: -1
      - mode: value
        value: About
        index: 0
        uses: -1
      - mode: value
        value: about
        index: 0
        uses: 1
